[package]
name = "linkr"
version = "0.1.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
url = "1.7.2"
diesel = { version = "1.0.0", features = ["postgres"] }

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["handlebars_templates", "tera_templates", "diesel_postgres_pool"]